those_words={
        'fuck':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'rand':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'madarchod':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bhosadike':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'gandu':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'laudu':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'lauda':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bhenchod':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'shit':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bullshit':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'motherfucker':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bhen ki chut':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'maa ki chut':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'randi':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'randi ki aaulad':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'fucker':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bitch':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bhadva':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'chutiya':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'chodu':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'chod':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'lund':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'sex':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'sexy':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'cunt':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'hijra':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'betichod':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'kutta':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'kutiya':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'saala':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'saali':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'jhaat':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bhosdi':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bhosda':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bhosad':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'burr':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'choot':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'lavde':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'chut':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'fattu':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'arse':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'ass':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'arsehole':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'asshole':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'faggot':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'fart':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'fucking':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'nigga':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'nigger':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'badass':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bastard':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'boner':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'piss':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'pissed':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'bitches':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'stfu':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'crap':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'dickhead':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'tit':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'tits':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'jackass':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'},
        'jerk off':{'0':'Please don\'t abuse!!! We at JUET don\'t tolerate it!!'}
        }
